import { notFound } from "next/navigation";
import { requireSession } from "@/lib/auth";
import { row,rows } from "@/lib/db";
import { products,sources,statuses } from "@/lib/labels";
import { addFollowUp,assignInquiry,syncInquiryToCrm,updateCustomer,updateInquiry,updateInquiryDetails } from "./actions";

type Inquiry={id:number;inquiry_no:string;customer_id:number;primary_email:string;name:string|null;company:string|null;country:string|null;phone:string|null;alternate_emails:string|null;note:string|null;source:string;product_category:string;requirement:string;status:string;owner_id:number|null;owner_name:string|null;assigned_at:string|null;next_follow_up_at:string|null;deal_amount:number|null;currency:string;created_at:string};

export default async function Detail({params}:{params:Promise<{id:string}>}){
  const s=await requireSession(),id=Number((await params).id);
  const q=row<Inquiry>("SELECT i.*,c.primary_email,c.name,c.company,c.country,c.phone,c.alternate_emails,c.note,u.display_name owner_name FROM inquiries i JOIN customers c ON c.id=i.customer_id LEFT JOIN users u ON u.id=i.owner_id WHERE i.id=?",id);
  if(!q||(s.role==="SALES"&&q.owner_id!==s.id))notFound();
  const staff=rows<any>("SELECT id,display_name,level FROM users WHERE role='SALES' AND active=1 ORDER BY id");
  const follows=rows<any>("SELECT f.*,u.display_name user_name FROM follow_ups f JOIN users u ON u.id=f.user_id WHERE inquiry_id=? ORDER BY f.created_at DESC",id);
  const crmSync=row<any>("SELECT * FROM crm_syncs WHERE inquiry_id=?",id);
  return <>
    <div className="topline"><div><div className="title">{q.inquiry_no}</div><p className="subtle">{q.company||q.name||q.primary_email} · {q.product_category}</p></div><span className="badge badge-green">{statuses[q.status]}</span></div>
    <section className="panel"><div className="meta"><div><label>客户邮箱（唯一标识）</label>{q.primary_email}</div><div><label>询盘来源</label>{sources[q.source]}</div><div><label>当前负责人</label>{q.owner_name||"尚未分配"}</div><div><label>收到时间</label>{q.created_at.slice(0,16)}</div><div><label>下次跟进</label>{q.next_follow_up_at||"未设置"}</div><div><label>成交金额</label>{q.deal_amount?`${q.currency} ${q.deal_amount}`:"—"}</div></div><div className="field"><strong>客户需求</strong><div style={{whiteSpace:"pre-wrap"}}>{q.requirement}</div></div></section>
    {s.role==="LEADER"&&<section className="panel"><div className="toolbar"><strong>编辑询盘资料</strong><span className="subtle">仅领导可修改，保存后写入操作日志</span></div><form action={updateInquiryDetails}><input type="hidden" name="id" value={id}/><div className="grid2"><label className="field">客户主邮箱 *<input name="email" type="email" required defaultValue={q.primary_email}/></label><label className="field">询盘来源<select name="source" defaultValue={q.source}>{Object.entries(sources).map(([v,l])=><option value={v} key={v}>{l}</option>)}</select></label><label className="field">产品分类<select name="product" defaultValue={q.product_category}>{products.map(p=><option key={p}>{p}</option>)}</select></label></div><label className="field">客户需求 *<textarea name="requirement" required defaultValue={q.requirement}/></label><button className="btn">保存询盘修改</button></form></section>}
    {s.role==="LEADER"&&<section className="panel"><strong>询盘分配</strong><form action={assignInquiry} className="actions" style={{marginTop:14}}><input type="hidden" name="id" value={id}/><select name="owner">{staff.map(u=><option value={u.id} key={u.id}>{u.display_name}（资深）</option>)}</select><button className="btn btn-primary">{q.owner_id?"重新分配":"确认分配"}</button></form></section>}
    <section className="panel"><div className="toolbar"><div><strong>悟空CRM建档</strong><p className="subtle">使用当前负责人的悟空CRM账号创建客户和联系人</p></div>{crmSync?.crm_contact_created?<span className="badge badge-green">已同步 · 客户 #{crmSync.crm_customer_id}</span>:<form action={syncInquiryToCrm}><input type="hidden" name="id" value={id}/><button className="btn btn-primary" disabled={!q.owner_id}>一键建档到悟空CRM</button></form>}</div>{!q.owner_id&&<p className="subtle">请先分配业务员。</p>}{crmSync?.last_error&&<div className="error">上次同步失败：{crmSync.last_error}</div>}</section>
    <div className="grid2"><section className="panel"><strong>新增跟进</strong><form action={addFollowUp}><input type="hidden" name="id" value={id}/><label className="field">沟通方式<select name="method"><option>邮件</option><option>电话</option><option>WhatsApp</option><option>在线聊天</option><option>视频会议</option><option>其他</option></select></label><label className="field">沟通摘要 *<textarea name="content" required/></label><label className="field">客户回复原文<textarea name="reply"/></label><label className="field">下次跟进时间<input type="datetime-local" name="next"/></label><button className="btn btn-primary" disabled={!q.owner_id}>保存跟进</button>{!q.owner_id&&<p className="subtle">分配给业务员后才可跟进。</p>}</form></section>
    <section className="panel"><strong>状态与结果</strong><form action={updateInquiry}><input type="hidden" name="id" value={id}/><label className="field">当前状态<select name="status" defaultValue={q.status}>{Object.entries(statuses).filter(([v])=>v!=="UNASSIGNED").map(([v,l])=><option value={v} key={v}>{l}</option>)}</select></label><label className="field">下次跟进时间<input type="datetime-local" name="next" defaultValue={q.next_follow_up_at?.replace(" ","T")||""}/></label><label className="field">成交金额（USD）<input type="number" step="0.01" name="amount" defaultValue={q.deal_amount||""}/></label><button className="btn btn-primary" disabled={!q.owner_id}>更新状态</button></form></section></div>
    <section className="panel"><strong>客户资料</strong><form action={updateCustomer}><input type="hidden" name="inquiryId" value={id}/><div className="grid2"><label className="field">联系人<input name="name" defaultValue={q.name||""}/></label><label className="field">公司<input name="company" defaultValue={q.company||""}/></label><label className="field">国家/地区<input name="country" defaultValue={q.country||""}/></label><label className="field">电话 / WhatsApp<input name="phone" defaultValue={q.phone||""}/></label><label className="field">关联邮箱<input name="alternate_emails" defaultValue={q.alternate_emails||""} placeholder="个人邮箱、公司其他邮箱；多个用逗号分隔"/></label></div><label className="field">客户备注<textarea name="note" defaultValue={q.note||""}/></label><button className="btn">保存客户资料</button></form></section>
    <section className="panel"><strong>跟进时间线</strong><div className="timeline" style={{marginTop:20}}>{follows.map(f=><div className="event" key={f.id}><strong>{f.user_name} · {f.method}</strong><p>{f.content}</p>{f.customer_reply&&<p className="subtle">客户回复：{f.customer_reply}</p>}<small>{f.created_at}{f.next_follow_up_at&&` · 下次跟进 ${f.next_follow_up_at}`}</small></div>)}{follows.length===0&&<p className="subtle">还没有跟进记录。</p>}</div></section>
  </>
}
