import { notFound } from "next/navigation";
import { requireSession } from "@/lib/auth";
import { row,rows } from "@/lib/db";
import { products,sources,statuses,salesProgressStatuses } from "@/lib/labels";
import { acceptInquiry,assignInquiry,syncInquiryToCrm,updateCustomer,updateInquiry,updateInquiryDetails } from "./actions";

type Inquiry={id:number;inquiry_no:string;customer_id:number;primary_email:string;name:string|null;company:string|null;country:string|null;phone:string|null;alternate_emails:string|null;note:string|null;source:string;product_category:string;requirement:string;status:string;owner_id:number|null;owner_name:string|null;assigned_at:string|null;accepted_at:string|null;accept_method:string|null;next_follow_up_at:string|null;deal_amount:number|null;currency:string;created_at:string};

export default async function Detail({params}:{params:Promise<{id:string}>}){
  const s=await requireSession(),id=Number((await params).id);
  const q=row<Inquiry>("SELECT i.*,c.primary_email,c.name,c.company,c.country,c.phone,c.alternate_emails,c.note,u.display_name owner_name FROM inquiries i JOIN customers c ON c.id=i.customer_id LEFT JOIN users u ON u.id=i.owner_id WHERE i.id=?",id);
  if(!q||(s.role==="SALES"&&q.owner_id!==s.id))notFound();
  const staff=rows<any>(`SELECT u.id,u.display_name,u.level,
    (SELECT i.assigned_at FROM inquiries i WHERE i.owner_id=u.id AND i.assigned_at IS NOT NULL ORDER BY i.assigned_at DESC LIMIT 1) last_assigned_at,
    (SELECT i.product_category FROM inquiries i WHERE i.owner_id=u.id AND i.assigned_at IS NOT NULL ORDER BY i.assigned_at DESC LIMIT 1) last_product
    FROM users u WHERE u.role='SALES' AND u.active=1 ORDER BY u.id`);
  const follows=rows<any>("SELECT f.*,u.display_name user_name FROM follow_ups f JOIN users u ON u.id=f.user_id WHERE inquiry_id=? ORDER BY f.created_at DESC",id);
  const crmSync=row<any>("SELECT * FROM crm_syncs WHERE inquiry_id=?",id);
  return <>
    <div className="topline"><div><div className="title">{q.inquiry_no}</div><p className="subtle">{q.company||q.name||q.primary_email} · {q.product_category}</p></div><span className="badge badge-green">{statuses[q.status]}</span></div>
    <section className="panel"><div className="meta"><div><label>客户邮箱（唯一标识）</label>{q.primary_email}</div><div><label>询盘来源</label>{sources[q.source]}</div><div><label>当前负责人</label>{q.owner_name||"尚未分配"}</div><div><label>收到时间</label>{q.created_at.slice(0,16)}</div><div><label>下次跟进</label>{q.next_follow_up_at||"未设置"}</div><div><label>成交金额</label>{q.deal_amount?`${q.currency} ${q.deal_amount}`:"—"}</div></div><div className="field"><strong>客户需求</strong><div style={{whiteSpace:"pre-wrap"}}>{q.requirement}</div></div></section>
    {s.role==="LEADER"&&<section className="panel"><div className="toolbar"><strong>编辑询盘资料</strong><span className="subtle">仅领导可修改，保存后写入操作日志</span></div><form action={updateInquiryDetails}><input type="hidden" name="id" value={id}/><div className="grid2"><label className="field">客户主邮箱 *<input name="email" type="email" required defaultValue={q.primary_email}/></label><label className="field">询盘来源<select name="source" defaultValue={q.source}>{Object.entries(sources).map(([v,l])=><option value={v} key={v}>{l}</option>)}</select></label><label className="field">产品分类<select name="product" defaultValue={q.product_category}>{products.map(p=><option key={p}>{p}</option>)}</select></label></div><label className="field">客户需求 *<textarea name="requirement" required defaultValue={q.requirement}/></label><button className="btn">保存询盘修改</button></form></section>}
    {s.role==="LEADER"&&<section className="panel"><div className="toolbar"><strong>询盘分配</strong><span className="subtle">分配前可参考每位业务员最近一次接收记录</span></div><table className="table"><thead><tr><th>业务员</th><th>上次收到询盘时间</th><th>上次询盘产品</th></tr></thead><tbody>{staff.map(u=><tr key={u.id}><td><strong>{u.display_name}</strong></td><td>{u.last_assigned_at?.slice(0,16)||"尚未分配"}</td><td>{u.last_product||"—"}</td></tr>)}</tbody></table><form action={assignInquiry} className="actions" style={{marginTop:18}}><input type="hidden" name="id" value={id}/><select name="owner">{staff.map(u=><option value={u.id} key={u.id}>{u.display_name}（资深）{u.last_product?` · 上次 ${u.last_product}`:" · 尚未分配"}</option>)}</select><button className="btn btn-primary">{q.owner_id?"重新分配":"确认分配"}</button></form></section>}
    <section className="panel"><div className="toolbar"><div><strong>悟空CRM建档</strong><p className="subtle">使用当前负责人的悟空CRM账号创建客户和联系人</p></div>{crmSync?.crm_contact_created?<span className="badge badge-green">已同步 · 客户 #{crmSync.crm_customer_id}</span>:<form action={syncInquiryToCrm}><input type="hidden" name="id" value={id}/><button className="btn btn-primary" disabled={!q.owner_id}>一键建档到悟空CRM</button></form>}</div>{!q.owner_id&&<p className="subtle">请先分配业务员。</p>}{crmSync?.last_error&&<div className="error">上次同步失败：{crmSync.last_error}</div>}</section>
    <div className="grid2"><section className="panel"><strong>接受询盘</strong>{q.accepted_at?<div style={{marginTop:18}}><span className="badge badge-green">已接受</span><p>沟通方式：{q.accept_method}</p><p className="subtle">接受时间：{q.accepted_at.slice(0,16)} · 下次提醒已自动设置为3天后</p></div>:s.role==="SALES"?<form action={acceptInquiry}><input type="hidden" name="id" value={id}/><label className="field">沟通方式<select name="method"><option>邮件</option><option>WhatsApp</option><option>邮件 + WhatsApp</option><option>电话</option><option>在线聊天</option><option>视频会议</option><option>其他</option></select></label><p className="subtle">请先通过所选方式联系客户，再点击接受询盘。系统将自动设置3天后的提醒。</p><button className="btn btn-primary" disabled={!q.owner_id}>接受询盘</button></form>:<p className="subtle" style={{marginTop:18}}>等待业务员接受。分配后48小时仍未接受会触发提醒。</p>}</section>
    <section className="panel"><strong>状态与结果</strong><form action={updateInquiry}><input type="hidden" name="id" value={id}/><label className="field">当前进度<select name="status" defaultValue={q.status==="NEW"?"CONTACTING":q.status}>{Object.entries(salesProgressStatuses).map(([v,l])=><option value={v} key={v}>{l}</option>)}</select></label><button className="btn btn-primary" disabled={!q.owner_id||(!q.accepted_at&&s.role==="SALES")}>更新进度</button></form><div className="reminder-rules"><strong>自动提醒规则</strong><p>需求确认：3天后 · 技术沟通：3天后 · 已报价：3天后</p><p>商务谈判：4天后 · 已成交：不再提醒</p><p className="subtle">业务员须先接受询盘；分配后48小时仍未接受，按未回复提醒。</p></div></section></div>
    <section className="panel"><strong>客户资料</strong><form action={updateCustomer}><input type="hidden" name="inquiryId" value={id}/><div className="grid2"><label className="field">联系人<input name="name" defaultValue={q.name||""}/></label><label className="field">公司<input name="company" defaultValue={q.company||""}/></label><label className="field">国家/地区<input name="country" defaultValue={q.country||""}/></label><label className="field">电话 / WhatsApp<input name="phone" defaultValue={q.phone||""}/></label><label className="field">关联邮箱<input name="alternate_emails" defaultValue={q.alternate_emails||""} placeholder="个人邮箱、公司其他邮箱；多个用逗号分隔"/></label></div><label className="field">客户备注<textarea name="note" defaultValue={q.note||""}/></label><button className="btn">保存客户资料</button></form></section>
    <section className="panel"><strong>跟进时间线</strong><div className="timeline" style={{marginTop:20}}>{follows.map(f=><div className="event" key={f.id}><strong>{f.user_name} · {f.method}</strong><p>{f.content}</p>{f.customer_reply&&<p className="subtle">客户回复：{f.customer_reply}</p>}<small>{f.created_at}{f.next_follow_up_at&&` · 下次跟进 ${f.next_follow_up_at}`}</small></div>)}{follows.length===0&&<p className="subtle">还没有跟进记录。</p>}</div></section>
  </>
}
