"use server";import { requireLeader } from "@/lib/auth";import { audit,db,row } from "@/lib/db";import { decryptSecret } from "@/lib/secrets";import { redirect } from "next/navigation";
export async function createInquiry(formData:FormData){const s=await requireLeader();const email=String(formData.get("email")||"").trim().toLowerCase();if(!email.includes("@"))throw new Error("邮箱格式不正确");let customer=row<{id:number}>("SELECT id FROM customers WHERE primary_email=? COLLATE NOCASE",email);if(!customer){const r=db.prepare("INSERT INTO customers(primary_email,name,company,country,phone,note) VALUES(?,?,?,?,?,?)").run(email,String(formData.get("name")||""),String(formData.get("company")||""),String(formData.get("country")||""),String(formData.get("phone")||""),String(formData.get("note")||""));customer={id:Number(r.lastInsertRowid)};audit(s.id,"CREATE","CUSTOMER",customer.id,`创建客户 ${email}`)}const r=db.prepare("INSERT INTO inquiries(customer_id,source,product_category,requirement,created_by) VALUES(?,?,?,?,?)").run(customer.id,String(formData.get("source")),String(formData.get("product")),String(formData.get("requirement")),s.id);const id=Number(r.lastInsertRowid),no=`INQ-${new Date().getFullYear()}-${String(id).padStart(4,"0")}`;db.prepare("UPDATE inquiries SET inquiry_no=? WHERE id=?").run(no,id);audit(s.id,"CREATE","INQUIRY",id,`录入询盘 ${no}`,{email});redirect(`/inquiries/${id}`)}

const schema={type:"object",additionalProperties:false,properties:{email:{type:"string"},name:{type:"string"},company:{type:"string"},country:{type:"string"},phone:{type:"string"},product:{type:"string",enum:["中大型SF6回收车","小型SF6回收车","SF6分析仪","仪表类","非自营产品","氢气产品","其他"]},requirement:{type:"string"},note:{type:"string"}},required:["email","name","company","country","phone","product","requirement","note"]};
const instructions=`你是外贸询盘信息提取助手。根据客户邮件或在线聊天原文，提取客户邮箱、姓名、公司、国家、电话/WhatsApp、产品分类、完整需求摘要和补充备注。不要虚构缺失信息，缺失字段返回空字符串。产品分类必须从给定枚举中选择。回收处理量较大、设备级或固定式方案归为中大型SF6回收车；便携或小容量归为小型SF6回收车。requirement 用中文清晰概括，但保留型号、数量、技术参数、目的地等关键信息。只输出JSON。`;

export async function analyzeInquiry(raw:string){
  await requireLeader();if(!raw.trim())return {ok:false,error:"请先粘贴询盘原文"} as const;
  const get=(key:string)=>row<{value:string}>("SELECT value FROM app_settings WHERE key=?",key)?.value;
  const protocol=get("ai_protocol")||"RESPONSES",endpoint=get("ai_endpoint"),model=get("ai_model")||"gpt-5.5",encryptedKey=get("ai_api_key");
  if(!endpoint||!encryptedKey)return {ok:false,error:"请先在“AI接口配置”中填写请求地址和 API Key"} as const;
  let apiKey:string;try{apiKey=decryptSecret(encryptedKey)}catch{return {ok:false,error:"API Key 无法解密，请在配置页重新填写"} as const}
  const body=protocol==="RESPONSES"?{model,instructions,input:raw,store:false,reasoning:{effort:"low"},max_output_tokens:1200,text:{format:{type:"json_schema",name:"inquiry_extraction",strict:true,schema}}}:{model,messages:[{role:"system",content:instructions+`\nJSON字段：email,name,company,country,phone,product,requirement,note`},{role:"user",content:raw}],response_format:{type:"json_object"}};
  try{const response=await fetch(endpoint,{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${apiKey}`},body:JSON.stringify(body),signal:AbortSignal.timeout(90000)});const data=await response.json().catch(()=>null) as any;if(!response.ok)return {ok:false,error:`AI接口返回 ${response.status}：${data?.error?.message||"请求失败"}`} as const;let text=protocol==="RESPONSES"?data?.output_text:data?.choices?.[0]?.message?.content;if(!text&&protocol==="RESPONSES")text=data?.output?.flatMap((x:any)=>x.content||[]).find((x:any)=>x.type==="output_text")?.text;if(typeof text!=="string")return {ok:false,error:"AI接口未返回可识别的文本内容"} as const;text=text.trim().replace(/^```(?:json)?\s*/i,"").replace(/\s*```$/,"");const result=JSON.parse(text);return {ok:true,data:{email:String(result.email||""),name:String(result.name||""),company:String(result.company||""),country:String(result.country||""),phone:String(result.phone||""),product:schema.properties.product.enum.includes(result.product)?result.product:"其他",requirement:String(result.requirement||raw),note:String(result.note||"")}} as const}catch(error){const cause=(error as any)?.cause;const detail=[cause?.code,cause?.address,cause?.port].filter(Boolean).join(" ");return {ok:false,error:error instanceof Error?`AI识别失败：${error.message}${detail?`（${detail}）`:""}`:"AI识别失败"} as const}
}
