"use client";
import { useState,useTransition } from "react";
import { analyzeInquiry,createInquiry } from "./actions";
import { products,sources } from "@/lib/labels";

const empty={email:"",name:"",company:"",country:"",phone:"",product:products[0],requirement:"",note:""};
export function InquiryForm(){
  const [raw,setRaw]=useState("");const [form,setForm]=useState(empty);const [message,setMessage]=useState("");const [pending,startTransition]=useTransition();
  const set=(key:string,value:string)=>setForm(v=>({...v,[key]:value}));
  function analyze(){setMessage("");startTransition(async()=>{const result=await analyzeInquiry(raw);if(result.ok){setForm(result.data);setMessage("识别完成，请核对后保存。")}else setMessage(result.error)})}
  return <><section className="panel"><div className="toolbar"><strong>第一步：粘贴询盘原文</strong><span className="subtle">邮件正文或在线聊天内容均可</span></div><textarea style={{width:"100%",minHeight:180,padding:12,border:"1px solid #ccd5e0",borderRadius:8}} value={raw} onChange={e=>setRaw(e.target.value)} placeholder="粘贴完整询盘内容，包括发件人邮箱、签名和客户需求……"/><p className="subtle">点击识别后，以上内容会发送到你在“AI接口配置”中设置的服务商。</p><button type="button" className="btn btn-primary" onClick={analyze} disabled={pending}>{pending?"AI正在识别…":"AI识别并填写"}</button>{message&&<p className={message.startsWith("识别完成")?"subtle":"error"}>{message}</p>}</section><form action={createInquiry} className="panel"><div className="toolbar"><strong>第二步：核对并保存</strong><span className="subtle">AI不会直接创建询盘</span></div><div className="grid2"><label className="field">客户邮箱 *<input name="email" type="email" required value={form.email} onChange={e=>set("email",e.target.value)}/></label><label className="field">联系人<input name="name" value={form.name} onChange={e=>set("name",e.target.value)}/></label><label className="field">公司名称<input name="company" value={form.company} onChange={e=>set("company",e.target.value)}/></label><label className="field">国家/地区<input name="country" value={form.country} onChange={e=>set("country",e.target.value)}/></label><label className="field">联系电话 / WhatsApp<input name="phone" value={form.phone} onChange={e=>set("phone",e.target.value)}/></label><label className="field">询盘来源<select name="source">{Object.entries(sources).map(([v,l])=><option value={v} key={v}>{l}</option>)}</select></label><label className="field">产品分类<select name="product" value={form.product} onChange={e=>set("product",e.target.value)}>{products.map(p=><option key={p}>{p}</option>)}</select></label></div><label className="field">客户明确需求 *<textarea name="requirement" required value={form.requirement} onChange={e=>set("requirement",e.target.value)}/></label><label className="field">客户备注<textarea name="note" value={form.note} onChange={e=>set("note",e.target.value)}/></label><button className="btn btn-primary">确认并保存询盘</button></form></>
}
